const WA='https://wa.me/995591244075?text='+encodeURIComponent('Здравствуйте! Хочу разобрать мой бизнес с Order & Profit.');
let lang=localStorage.getItem('op-lang')==='en'?'en':'ru';
const copy={
ru:{heroKicker:'БИЗНЕС-СИСТЕМЫ • БРЕНД • DIGITAL • РОСТ',hero1:'БИЗНЕС ДОЛЖЕН',hero2:'РАБОТАТЬ',hero3:'КАК СИСТЕМА.',heroText:'Находим, где бизнес теряет деньги, клиентов и время. Выстраиваем управление, процессы и команду, полностью брендируем бизнес, создаём digital-систему и подключаем продвижение.',seeProducts:'Смотреть доказательства ↓',diagnoseBtn:'Разобрать мой бизнес',diagTitle:'Что сейчас<br>тормозит ваш бизнес?',diagLead:'Выберите то, что похоже на вашу ситуацию. Начнём с причины, а не с продажи случайной услуги.',prob1:'Клиентов мало, меня плохо находят',prob2:'Сайт есть, но он не приводит заявки',prob3:'Всё вручную, бизнес зависит от меня',prob4:'Бизнес выглядит слабее конкурентов',prob5:'Не хватает системы, команды и контроля',prob6:'Проблем много, не понимаю с чего начать',productsTitle:'Не обещания.<br>Работающие решения.',productsLead:'Откройте реальные продукты. Мы показываем то, что уже работает.',workTitle:'Реальные проекты.<br>Можно открыть.',workLead:'Не концепты и не картинки. Живые проекты для реального бизнеса.',aboutTitle:'Сначала бизнес.<br>Потом инструменты.',aboutText:'Order & Profit смотрит на компанию глазами собственника: где теряются деньги, почему всё держится на одном человеке, что мешает команде работать и где клиент уходит к конкуренту.',aboutText2:'Мы соединяем управленческий опыт, бизнес-процессы, полный брендинг, digital, SEO, контент и автоматизацию в одну систему. Поэтому решение начинается не с вопроса «какой сайт сделать?», а с вопроса «что должно измениться в бизнесе?».',finalTitle:'РАЗБЕРЁМ<br>ВАШ БИЗНЕС?',writeUs:'Написать в WhatsApp ↗',startDiag:'Вернуться к диагностике'},
en:{heroKicker:'BUSINESS SYSTEMS • BRAND • DIGITAL • GROWTH',hero1:'BUSINESS SHOULD',hero2:'WORK',hero3:'AS A SYSTEM.',heroText:'We find where a business loses money, customers and time. Then we build management, processes and teams, create the full brand, digital system and growth engine.',seeProducts:'See the proof ↓',diagnoseBtn:'Diagnose my business',diagTitle:'What is holding<br>your business back?',diagLead:'Choose the situation that feels familiar. We start with the cause, not a random service.',prob1:'Not enough customers or local visibility',prob2:'The website exists but does not generate leads',prob3:'Everything is manual and depends on me',prob4:'The business looks weaker than competitors',prob5:'We lack structure, team and control',prob6:'Too many problems, I do not know where to start',productsTitle:'Not promises.<br>Working solutions.',productsLead:'Open real products. We show what already works.',workTitle:'Real projects.<br>Open them.',workLead:'Not concepts or mockups. Live work for real businesses.',aboutTitle:'Business first.<br>Tools second.',aboutText:'Order & Profit looks at a company through the owner’s eyes: where money leaks, why everything depends on one person, what blocks the team and where customers choose competitors.',aboutText2:'We connect management experience, business processes, full branding, digital, SEO, content and automation into one system. The first question is not “what website should we build?” but “what must change in the business?”.',finalTitle:'LET’S FIX<br>YOUR BUSINESS?',writeUs:'Message on WhatsApp ↗',startDiag:'Back to diagnosis'}};
function applyLang(l){lang=l;localStorage.setItem('op-lang',l);document.documentElement.lang=l;document.querySelectorAll('[data-i18n]').forEach(el=>{let k=el.dataset.i18n;if(copy[l][k])el.innerHTML=copy[l][k]});document.querySelectorAll('[data-setlang]').forEach(b=>b.classList.toggle('on',b.dataset.setlang===l));renderJourney();}
document.querySelectorAll('[data-setlang]').forEach(b=>b.onclick=()=>applyLang(b.dataset.setlang));
window.addEventListener('load',()=>setTimeout(()=>document.querySelector('.preload')?.classList.add('off'),250));
const nav=document.querySelector('.nav .keep');if(nav){nav.href=WA;nav.target='_blank';nav.textContent='WHATSAPP'}
function renderJourney(){
 const old=document.querySelector('.sales-journey');if(old)old.remove();
 const diag=document.querySelector('#diagnose');if(!diag)return;
 const s=document.createElement('section');s.className='sales-journey';
 s.innerHTML=lang==='ru'?`<div class="eyebrow">02 / КАК МЫ РЕШАЕМ</div><h2>ОДНА ПРОБЛЕМА.<br><span>ЦЕЛАЯ СИСТЕМА.</span></h2><p class="journey-lead">Мы не начинаем с сайта, логотипа или рекламы. Сначала понимаем, почему бизнес недополучает результат. Затем собираем нужную систему.</p><div class="journey-grid"><article><em>01</em><b>УПРАВЛЕНИЕ</b><p>Структура компании, роли, ответственность, контроль, отчётность, управленческие ритмы и принятие решений.</p></article><article><em>02</em><b>ПРОЦЕССЫ И КОМАНДА</b><p>Проектирование и внедрение бизнес-процессов, подбор кадров, формирование команды и управленческие тренинги.</p></article><article><em>03</em><b>ПОЛНОЕ БРЕНДИРОВАНИЕ</b><p>Позиционирование, фирменный стиль, логотип, оформление точки, меню, полиграфия, упаковка, наружная реклама и соцсети.</p></article><article><em>04</em><b>DIGITAL-СИСТЕМА</b><p>Сайты, приложения, CRM, автоматизация, системы заказов и бронирования, калькуляторы и собственные цифровые продукты.</p></article><article><em>05</em><b>ПРОДВИЖЕНИЕ</b><p>SEO, Google Business, локальный поиск, контент, фото и видео, рекламные материалы и система привлечения клиентов.</p></article><article class="journey-result"><em>→</em><b>РЕЗУЛЬТАТ</b><p>Бизнес выглядит сильнее, работает понятнее, меньше зависит от ручного управления и лучше превращает внимание в продажи.</p></article></div><a class="journey-cta" href="${WA}" target="_blank">РАЗОБРАТЬ МОЙ БИЗНЕС В WHATSAPP ↗</a>`:`<div class="eyebrow">02 / HOW WE SOLVE IT</div><h2>ONE PROBLEM.<br><span>ONE COMPLETE SYSTEM.</span></h2><p class="journey-lead">We do not start with a website, logo or advertising. First we find what is holding the business back. Then we build the system it actually needs.</p><div class="journey-grid"><article><em>01</em><b>MANAGEMENT</b><p>Structure, roles, accountability, control, reporting and decision-making.</p></article><article><em>02</em><b>PROCESS & TEAM</b><p>Business processes, hiring, team formation and management training.</p></article><article><em>03</em><b>FULL BRANDING</b><p>Positioning, identity, logo, physical touchpoints, print, packaging, signage and social presence.</p></article><article><em>04</em><b>DIGITAL SYSTEM</b><p>Websites, apps, CRM, automation, ordering, booking, calculators and custom digital products.</p></article><article><em>05</em><b>GROWTH</b><p>SEO, Google Business, local search, content, photo, video and customer acquisition.</p></article><article class="journey-result"><em>→</em><b>RESULT</b><p>A stronger business that is easier to manage, easier to understand and easier to buy from.</p></article></div><a class="journey-cta" href="${WA}" target="_blank">DIAGNOSE MY BUSINESS ON WHATSAPP ↗</a>`;
 diag.insertAdjacentElement('afterend',s);
}
function reorder(){const main=document.querySelector('main'),hero=document.querySelector('.hero'),marquee=document.querySelector('.marquee'),diag=document.querySelector('#diagnose'),products=document.querySelector('#products'),statement=document.querySelector('.statement');if(!main||!hero||!diag)return;hero.insertAdjacentElement('afterend',marquee);marquee.insertAdjacentElement('afterend',diag);diag.classList.add('sales-pain');renderJourney();const journey=document.querySelector('.sales-journey');journey.insertAdjacentElement('afterend',products);products.insertAdjacentElement('afterend',statement);}
const solutions={ru:[['ВАМ НУЖНА СИСТЕМА ПРИВЛЕЧЕНИЯ','Проверяем позиционирование, Google, локальный SEO, сайт и путь клиента. Затем исправляем точки, где теряется спрос.'],['ВАМ НУЖЕН НЕ «НОВЫЙ ДИЗАЙН»','Разбираем оффер, доверие, структуру и путь до обращения. Сайт должен вести к действию, а не просто существовать.'],['НУЖНА УПРАВЛЯЕМАЯ СИСТЕМА','Разбираем процессы, роли, ответственность и ручные операции. Автоматизируем только после того, как понятна правильная логика работы.'],['НУЖНО ПОЛНОЕ БРЕНДИРОВАНИЕ','Собираем единый образ бизнеса: позиционирование, визуальный стиль, сайт, соцсети, полиграфию, упаковку и физические точки контакта.'],['НУЖНА УПРАВЛЕНЧЕСКАЯ СИСТЕМА','Структура, процессы, кадры, ответственность, контроль, отчётность и обучение руководителей. Цель: бизнес не должен держаться только на собственнике.'],['НАЧИНАЕМ С ДИАГНОСТИКИ','Разбираем управление, процессы, команду, продажи, бренд и digital. После этого определяем три первых действия по приоритету.']],en:[['YOU NEED AN ACQUISITION SYSTEM','We audit positioning, Google, local SEO, website and customer journey, then fix where demand is being lost.'],['YOU DO NOT JUST NEED A REDESIGN','We audit the offer, trust, structure and conversion path. A website should lead to action, not merely exist.'],['YOU NEED A MANAGEABLE SYSTEM','We map processes, roles, accountability and manual work, then automate the right workflow.'],['YOU NEED FULL BRANDING','We build one coherent business image across positioning, identity, web, social, print, packaging and physical touchpoints.'],['YOU NEED A MANAGEMENT SYSTEM','Structure, processes, hiring, accountability, control, reporting and management training so the company does not depend on one owner.'],['START WITH DIAGNOSIS','We assess management, process, team, sales, brand and digital, then define the first three priorities.']]};
function showSolution(btn,i){document.querySelectorAll('.problem').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const el=document.querySelector('#solution'),x=solutions[lang][i];el.innerHTML=`<b class="solution-title">${x[0]}</b><p>${x[1]}</p><a class="solution-wa" href="${WA}" target="_blank">${lang==='ru'?'ОБСУДИТЬ ЭТО В WHATSAPP':'DISCUSS THIS ON WHATSAPP'} ↗</a>`;el.classList.add('show');if(innerWidth<900)setTimeout(()=>el.scrollIntoView({behavior:'smooth',block:'center'}),80)}
document.querySelectorAll('.problem').forEach((b,i)=>b.onclick=e=>{e.preventDefault();showSolution(b,i)});
const works=[['USTA','USTA','Home services / Web'],['HERMINE SALON','hermine-booking','Beauty / Booking'],['ARARAT ELIT','ararat-elit','Fitness & SPA / Digital'],['FASTFOOD','fastfood','Food / Ordering'],['FLOWERS','flowers','Retail / Web'],['GONCHARUK DENTAL','goncharuk-dental','Healthcare / Web'],['WAVE APP','wave-app-','Digital product / App'],['MIX FOOD','mix-food','Restaurant / Ordering system']];
const grid=document.querySelector('.work-grid');if(grid){const have=new Set([...grid.querySelectorAll('a')].map(a=>a.href));works.forEach(([name,slug,meta])=>{const url=`https://xugushik-source.github.io/${slug}/`;if(have.has(url))return;const a=document.createElement('a');a.className='work';a.target='_blank';a.href=url;a.innerHTML=`<iframe loading="lazy" src="${url}" title="${name}"></iframe><div class="cap"><div><b>${name}</b><br><span>${meta}</span></div><b>↗</b></div>`;grid.appendChild(a)})}
const finalPrimary=document.querySelector('.final .actions .primary');if(finalPrimary){finalPrimary.href=WA;finalPrimary.target='_blank'}
const foot=document.querySelector('.foot');if(foot&&!foot.querySelector('[href*="wa.me"]'))foot.insertAdjacentHTML('beforeend',`<a href="${WA}" target="_blank">WHATSAPP +995 591 244 075 ↗</a>`);
reorder();applyLang(lang);
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));